name: Lint and Test Pull Request

on: pull_request

jobs:
  lint_test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Setup tests
        run: |
          cp .env.test .env
          docker-compose up -d postgres-tcc
          npx mikro-orm migration:up
      - name: Run Tests
        run: npm run test
